name: 为了快速解决你遇到的问题, 请使用此模板进行提问
description: 运行wzry.py过程遇到的各种问题
title: "[windows][雷电模拟器][问题描述]"
labels: "WZRY-RUN-Error"
body:
  - type: markdown
    attributes:
      value: |
        - 💬请礼貌**友善**的提问
        - 🌟你可以为本项目点个[star](https://github.com/cndaqiang/WZRY), 我会更愉快的回答你的问题
  - type: checkboxes
    attributes:
      label: "请在阅读完下面的内容后再进行提问:"
      description: "[使用文档WZRY.doc](https://cndaqiang.github.io/wzry.doc/)包含最新版本的使用教程、问题收录、使用经验. 每天都有更新. 请在阅读后再进行提问."
      options:
        - label: "我已阅读全新的[项目主页](https://cndaqiang.github.io/wzry.doc/)"
        - label: "我已阅读全新的[安装指南](https://cndaqiang.github.io/wzry.doc/guide/install/)"
        - label: "我已搜索[常见问题收录](https://cndaqiang.github.io/wzry.doc/qa/qa), 并未找到类似问题"
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: "你当前正在使用的程序以及版本号"
      description: "你遇到的问题, 可能在最新的[stable版本](https://github.com/cndaqiang/WZRY/releases)中已经被修复了."
      options:
        - WZRY >= 2.2.8
        - WZRY == 2.2.8-stable
        - WZRY <= 2.2.6-stable
        - AutoWZRY >= 2.2.9a1
        - 其他
    validations:
      required: true
  - type: text
    id: other_version
    attributes:
      label: "如果选择了*其他*，请输入具体版本"
  - type: textarea
    attributes:
      label: "配置文件: `config.win.yaml`"
      description: "请在此处上传你的配置文件`config.win.yaml`截图或者粘贴到此处"
      value: |
          - mynode: 0
          - LINK_dict:
          -     0: Android:///127.0.0.1:5565
          - prefix: wzry
    validations:
      required: true
