name: 为了快速解决你遇到的问题, 请使用此模板进行提问
description: 运行wzry.py过程遇到的各种问题
title: "[windows][雷电模拟器][问题描述]"
labels: ["运行","模拟器","WZRY"]
body:
  - type: markdown
    attributes:
      value: |
        - 💬请礼貌**友善**的提问
        - 🌟你可以为本项目点个[star](https://github.com/cndaqiang/WZRY), 我会更愉快的回答你的问题
  - type: checkboxes
    attributes:
      label: "请在阅读完下面的内容后再进行提问:"
      description: "[使用文档WZRY.doc](https://cndaqiang.github.io/wzry.doc/)包含最新版本的使用教程、问题收录、使用经验. 每天都有更新. 请在阅读后再进行提问."
      options:
        - label: "我已阅读全新的[项目主页](https://cndaqiang.github.io/wzry.doc/)"
        - label: "我已阅读全新的[安装指南](https://cndaqiang.github.io/wzry.doc/guide/install/)"
        - label: "我已搜索[常见问题收录](https://cndaqiang.github.io/wzry.doc/qa/qa), 并未找到类似问题"
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: "你当前正在使用的程序以及版本号"
      description: "你遇到的问题, 可能在最新的[stable版本](https://github.com/cndaqiang/WZRY/releases)中已经被修复了."
      options:
        - WZRY >= 2.2.8
        - WZRY == 2.2.8-stable
        - WZRY <= 2.2.6-stable
        - AutoWZRY >= 2.2.9a1
        - 其他
    validations:
      required: true
  - type: textarea
    id: other_version
    attributes:
      label: "如果选择了其他，请输入具体版本"
      value: "WZRY-2.2.8"
  - type: textarea
    attributes:
      label: "配置文件: config.win.yaml"
      description: "请在此处填写你的配置文件或截图粘贴到此处"
      value: |
        # 例如
        mynode: 0
        totalnode: 2
        multiprocessing: True
        BlueStackdir: C:\Program Files\BlueStacks_nxt
        BlueStack_Instance:
            0: Pie64_1
            1: Pie64
        BlueStack_Windows:
            0: BlueStacks1
            1: BlueStacks0
        LINK_dict:
            0: Android:///127.0.0.1:5565
            1: Android:///127.0.0.1:5555
        prefix: wzry
        logfile:
            0: result.0.txt
            1: result.1.txt
    validations:
      required: true
  - type: textarea
    attributes:
      label: "控制文件: WZRY.0.运行模式.txt"
      description: "请在此处填写你的控制文件或截图粘贴到此处"
      value: |
        uptime=23.9
        self.对战时间=[1.0,uptime]
        self.限时组队时间=uptime
        # 选择对战线路和英雄
        分路名称=["对抗", "打野","中路","发育","游走"]
        线路坐标=[(-0.314, -0.26),  (-0.194, -0.26), (-0.069, -0.26), (0.037, -0.26),  (0.18, -0.26)]
        位置坐标=[(6,5),(9,5),(4,4),(9,2),(2,4)]
        index=(self.runstep+self.mynode)%len(分路名称)
        TimeECHO(f"本次{self.runstep}对战分路: {分路名称[index]}")
        #
        #主战英雄
        pos=位置坐标[index]
        参战英雄头像坐标=(-0.54+pos[0]*0.09,-0.31+pos[1]*0.11)
        self.Tool.cal_record_pos(参战英雄头像坐标, self.移动端.resolution, "参战英雄头像", savepos=True)
        self.Tool.cal_record_pos(线路坐标[index], self.移动端.resolution, "参战英雄线路", savepos=True)
        #备战英雄, 因为对抗、打野、游走之间的英雄会互相冲突, 所以这些位置冲突的时候换成其他路(发育3,中路2)
        index=[3,2,3,2,3][index]
        pos=位置坐标[index]
        参战英雄头像坐标=(-0.54+pos[0]*0.09,-0.31+pos[1]*0.11)
        self.Tool.cal_record_pos(参战英雄头像坐标, self.移动端.resolution, "备战英雄头像", savepos=True)
        self.Tool.cal_record_pos(线路坐标[index], self.移动端.resolution, "备战英雄线路", savepos=True)
    validations:
      required: true
