name: 为了快速解决你遇到的问题, 请使用此模板进行提问 
description: 运行wzry.py过程遇到的各种问题
title: '[windows][雷电模拟器][问题描述]'
labels: "label是什么"
body:
  - type: markdown
    attributes:
      value: |
      - '💬请礼貌**友善**的提问'
      - '🌟你可以为本项目点个[star](https://github.com/cndaqiang/WZRY), 我会更愉快的回答你的问题'
  - type: checkboxes
    attributes:
      label: '请在阅读完下面的内容后再进行提问:'
      description: '[使用文档WZRY.doc](https://cndaqiang.github.io/wzry.doc/)包含最新版本的使用教程、问题收录、使用经验. 每天都有更新. 请在阅读后再进行提问.'
      options:
      - label: '我已阅读全新的[项目主页](https://cndaqiang.github.io/wzry.doc/)'
        required: true
      - label: '我已阅读全新的[安装指南](https://cndaqiang.github.io/wzry.doc/guide/install/)'
        required: true
      - label: '我已搜索[常见问题收录](https://cndaqiang.github.io/wzry.doc/qa/qa), 并未找到类似问题'
        required: true
  - type: dropdown
    id: version
    attributes:
      label: '你当前正在使用的程序以及版本号'
      description: "请采用最新的[stable版本](https://github.com/cndaqiang/WZRY/releases)进行尝试."
      options:
        - WZRY >= 2.2.8
        - WZRY == 2.2.8-stable
        - WZRY <= 2.2.6-stable
        - AutoWZRY >= 2.2.9a1
        - 其他
    
  - type: checkboxes
    attributes:
      label: 'Is the component officially supported by the Appium team?'
      description: 'Make sure you report an issue for a component which is officially supported/maintained by the Appium team.'
      options:
      - label: 'I have verified the component repository is present under the Appium organization in GitHub'
        required: true
  - type: checkboxes
    attributes:
      label: 'Is there an existing issue for this?'
      description: 'Please [search :mag: the issues](https://github.com/appium/appium/issues) to check if this bug has already been reported.'
      options:
      - label: 'I have searched the existing issues'
        required: true
  - type: textarea
    attributes:
      label: '配置文件: `config.win.yaml`'
      description: '请在此处上传你的配置文件`config.win.yaml`截图或者粘贴到此处'
      value: |
                - "mynode: 0"
                - "totalnode: 2"
                - "multiprocessing: True"
                - "BlueStackdir: C:\Program Files\BlueStacks_nxt"
                - "BlueStack_Instance:"
                - "    0: Pie64_1"
                - "    1: Pie64"
                - "BlueStack_Windows:"
                - "    0: BlueStacks1"
                - "    1: BlueStacks0"
                - "LINK_dict:"
                - "    0: Android:///127.0.0.1:5565"
                - "    1: Android:///127.0.0.1:5555"
                - "prefix: wzry"
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Minimal Reproducible Example'
      description: |
        Please provide a the _smallest, complete code snippet_ that Appium's maintainers can run to reproduce the issue ([read more about what this entails](https://stackoverflow.com/help/minimal-reproducible-example)).  Failing this, any sort of reproduction steps are better than nothing!

        An easy way to get started is to copy [sample code](https://github.com/appium/appium/tree/master/packages/appium/sample-code) and modify it accordingly.

        If the result is more than a screenful of text _or_ requires multiple files, please:

        - _Attach_ (do not paste) it to this textarea, _or_
        - Put it in a [Gist](https://gist.github.com) and paste the link, _or_
        - Provide a link to a new or existing public repository exhibiting the issue
    validations:
      required: true
  - type: textarea
    attributes:
      label: 'Environment'
      description: 'Please provide the following information about your environment; feel free to remove any items which are not relevant.'
      value: |
          - Operating system:
          - Appium server version (output of `appium --version`):
          - Appium driver(s) and their version(s) (`appium driver list`):
          - Appium plugin(s) and their version(s) (`appium plugin list`):
          - Node.js version (output of `node --version`):
          - `npm` version (output of `npm --version`):
          - Last component(s) version which did _not_ exhibit the problem:
          - Platform and version under test:
          - Real device or emulator/simulator:
    validations:
      required: false
  - type: input
    attributes:
      label: 'Link to Appium Logs'
      description: |
        Create a [Gist](https://gist.github.com)—which contains your _full_ Appium logs—and link it here.  Alternatively, you can attach a logfile to this issue (drag it into the "Further Information" field below).

        :warning: _Remember to redact or remove any sensitive information!_
      placeholder: 'https://gist.github.com/...'
  - type: textarea
    attributes:
      label: Further Information
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        _Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in._
    validations:
      required: false
  - type: markdown
    attributes:
      value: ':stop_sign: _For support questions, please visit [http://discuss.appium.io](http://discuss.appium.io) instead._'
