name: 为了快速解决你遇到的问题, 请使用此模板进行提问
description: 运行wzry.py过程遇到的各种问题
title: "[windows][雷电模拟器][问题描述]"
labels: ["安装配置","模拟器","对战","礼包","组队"]
body:
  - type: markdown
    attributes:
      value: |
        - 🥰请礼貌**友善**的提问
        - ✨你可以为本项目点个star, 我会更愉快的回答你的问题
  - type: checkboxes
    attributes:
      label: "请在阅读完下面的内容后再进行提问:"
      description: "[使用文档WZRY.doc](https://cndaqiang.github.io/wzry.doc/)包含最新版本的使用教程、问题收录、使用经验. 每天都有更新. 请在阅读后再进行提问."
      options:
        - label: "我已阅读全新的[项目主页](https://cndaqiang.github.io/wzry.doc/)"
        - label: "我已阅读全新的[安装指南](https://cndaqiang.github.io/wzry.doc/guide/install/)"
        - label: "我已搜索[常见问题收录](https://cndaqiang.github.io/wzry.doc/qa/qa), 并未找到类似问题"
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: "你当前正在使用的程序以及版本号"
      description: |
        - 请尽可能的使用最新的[stable版本](https://github.com/cndaqiang/WZRY/releases)
        - 请尽可能的升级airtest_mobileauto`python -m pip install airtest_mobileauto --upgrade`
        - 你遇到的问题, 可能在最新的版本中已经被修复了.
      options:
        - WZRY == 2.2.9-stable
        - WZRY == 2.2.8-stable
        - AutoWZRY >= 2.2.9a1
        - 其他
    validations:
      required: true
  - type: textarea
    id: other_version
    attributes:
      label: "如果选择了其他，请输入具体版本"
      value: "WZRY-2.2.6"
  - type: textarea
    attributes:
      label: "配置文件: config.win.yaml"
      description: "请在此处填写或上传你的配置文件, 亦可截图粘贴到此处"
      value: |
        # 例如
        mynode: 0
        totalnode: 2
        multiprocessing: True
        BlueStackdir: C:\Program Files\BlueStacks_nxt
        BlueStack_Instance:
            0: Pie64_1
            1: Pie64
        BlueStack_Windows:
            0: BlueStacks1
            1: BlueStacks0
        LINK_dict:
            0: Android:///127.0.0.1:5565
            1: Android:///127.0.0.1:5555
        prefix: wzry
        logfile:
            0: result.0.txt
            1: result.1.txt
    validations:
      required: true
  - type: textarea
    attributes:
      label: "控制文件: WZRY.0.运行模式.txt"
      description: "请在此处填写或上传你的控制文件"
      value: |
        [此处支持: 填写文本、上传文件、粘贴截图]
        # 例如
        uptime=23.9
        self.对战时间=[1.0,uptime]
        self.限时组队时间=uptime
        # 选择对战线路和英雄
        分路名称=["对抗", "打野","中路","发育","游走"]
        线路坐标=[(-0.314, -0.26),  (-0.194, -0.26), (-0.069, -0.26), (0.037, -0.26),  (0.18, -0.26)]
        位置坐标=[(6,5),(9,5),(4,4),(9,2),(2,4)]
        index=(self.runstep+self.mynode)%len(分路名称)
        TimeECHO(f"本次{self.runstep}对战分路: {分路名称[index]}")
        #
        #主战英雄
        pos=位置坐标[index]
        参战英雄头像坐标=(-0.54+pos[0]*0.09,-0.31+pos[1]*0.11)
        self.Tool.cal_record_pos(参战英雄头像坐标, self.移动端.resolution, "参战英雄头像", savepos=True)
        self.Tool.cal_record_pos(线路坐标[index], self.移动端.resolution, "参战英雄线路", savepos=True)
        #备战英雄, 因为对抗、打野、游走之间的英雄会互相冲突, 所以这些位置冲突的时候换成其他路(发育3,中路2)
        index=[3,2,3,2,3][index]
        pos=位置坐标[index]
        参战英雄头像坐标=(-0.54+pos[0]*0.09,-0.31+pos[1]*0.11)
        self.Tool.cal_record_pos(参战英雄头像坐标, self.移动端.resolution, "备战英雄头像", savepos=True)
        self.Tool.cal_record_pos(线路坐标[index], self.移动端.resolution, "备战英雄线路", savepos=True)
    validations:
      required: true
  - type: textarea
    attributes:
      label: "执行结果: result.0.txt"
      description: "请在此处填写或上传你的执行结果"
      value: |
        [此处支持: 填写文本、上传文件、粘贴截图]
        # 例如
        [11-17 05:00:02]wzry0>控制端(linux)
        [11-17 05:00:02]wzry0>客户端(lin_docker)
        [11-17 05:00:02]wzry0>ADB =(/home/cndaqiang/.local/lib/python3.10/site-packages/airtest/core/android/static/adb/linux/adb)
        [11-17 05:00:02]wzry0>LINK(Android:///127.0.0.1:5555)
        [11-17 05:00:02]wzry0>LINKhead(Android:///127.0.0.1)
        [11-17 05:00:02]wzry0>LINKtype(android)
        [11-17 05:00:02]wzry0>LINKURL(127.0.0.1:5555)
        [11-17 05:00:02]wzry0>LINKport(5555)
        [11-17 05:00:02]wzry0>Android:///127.0.0.1:5555:开始第1/3次连接
        [11-17 05:00:10]wzry0>Android:///127.0.0.1:5555:链接失败
        [11-17 05:00:14]wzry0>没有找到ADB设备127.0.0.1:5555
        [11-17 05:10:41]wzry0>RUNINFO
        [11-17 05:10:41]wzry0>	 组队模式 = True
        [11-17 05:10:41]wzry0>	 房主 = True
        [11-17 05:10:41]wzry0>	 对战模式 = 5v5匹配
        [11-17 05:10:41]wzry0>	 对战时间 = [1.0,23.9]
        [11-17 05:10:41]wzry0>	 限时组队时间 = 23.9
        [11-17 05:10:41]wzry0>	 runstep = 119
        [11-17 05:10:41]wzry0>	 jinristep = 1
        [11-17 05:10:41]wzry0>	 青铜段位 = True
        [11-17 05:10:41]wzry0>	 标准模式 = True
        [11-17 05:10:41]wzry0>	 触摸对战 = True
    validations:
      required: true
  - type: textarea
    attributes:
      label: "运行目录截图"
      description: "请截图运行目录并粘贴到此处"
      value: |
        [此处支持: 填写文本、上传文件、粘贴截图]
        例如
        ![image](https://github.com/user-attachments/assets/a2eb219b-f485-44fe-bff2-a2a757f3999c)
  - type: textarea
    attributes:
      label: "模拟器设置页面"
      description: "请截图模拟器设置页面并粘贴到此处"
      value: |
        [此处支持: 填写文本、上传文件、粘贴截图]
        如果问题不涉及模拟器, 可以不填写此输入框.
        如果你涉及到连接不了模拟器，无法控制模拟器的问题，请在此处粘贴你的模拟器设置页面.
        需要确定你开启了ADB以及ADB的端口以及分辨率和dpi的设置.
        非`960x540`分辨率`dpi=160`的设备, 请自行解决.
        模拟器的安装路径, 多开页面截图等
        例如这个截图就非常充分
        ![image](https://github.com/user-attachments/assets/ce5ca8ce-c1a2-4ac0-a2e3-e1b3ad74f5e0)
  - type: textarea
    attributes:
      label: "游戏页面页面"
      description: "请截图游戏页面并粘贴到此处"
      value: |
        [此处支持: 填写文本、上传文件、粘贴截图]
        如果在游戏过程中遇到问题, 请在此处粘贴**出现问题的画面**
        比如, 无法进入对战时, 游戏内显示的什么画面
